version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_USER: ramez
      MYSQL_DATABASE: ssi
      MYSQL_PASSWORD: ramez
